"""add invitations table

Revision ID: a0c44aa007dd
Revises: d75fe944c53f
Create Date: 2026-09-10 22:51:07.198682
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'a0c44aa007dd'
down_revision: Union[str, None] = 'd75fe944c53f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invitations',
    sa.Column('invited_role', sa.Enum('TEACHER', name='invitation_role'), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('invite_token', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('SENT', 'SUBMITTED', 'APPROVED', 'REJECTED', 'EXPIRED', name='invitation_status'), nullable=False),
    sa.Column('submitted_data', sa.JSON(), nullable=True),
    sa.Column('invited_by', sa.UUID(), nullable=False),
    sa.Column('reviewed_by', sa.UUID(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_user_id', sa.UUID(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('institution_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['created_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.ForeignKeyConstraint(['invited_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invitations_email'), 'invitations', ['email'], unique=False)
    op.create_index(op.f('ix_invitations_institution_id'), 'invitations', ['institution_id'], unique=False)
    op.create_index(op.f('ix_invitations_invite_token'), 'invitations', ['invite_token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_invitations_invite_token'), table_name='invitations')
    op.drop_index(op.f('ix_invitations_institution_id'), table_name='invitations')
    op.drop_index(op.f('ix_invitations_email'), table_name='invitations')
    op.drop_table('invitations')
    # ### end Alembic commands ###