"""add email_failures table

Revision ID: ca5b2e8f6fde
Revises: ff3955f0f5c2
Create Date: 2026-09-12 16:44:26.493141
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'ca5b2e8f6fde'
down_revision: Union[str, None] = 'ff3955f0f5c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_failures',
    sa.Column('recipient', sa.String(length=255), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('email_type', sa.String(length=100), nullable=False),
    sa.Column('error_message', sa.String(length=1000), nullable=False),
    sa.Column('context', sa.JSON(), nullable=True),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('email_failures')
    # ### end Alembic commands ###