"""add teachers table

Revision ID: ff3955f0f5c2
Revises: a0c44aa007dd
Create Date: 2026-09-10 22:55:56.229892
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'ff3955f0f5c2'
down_revision: Union[str, None] = 'a0c44aa007dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teachers',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('gender', sa.Enum('MALE', 'FEMALE', 'OTHER', 'PREFER_NOT_TO_SAY', name='gender'), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('qualification', sa.String(length=255), nullable=False),
    sa.Column('specialization', sa.String(length=255), nullable=True),
    sa.Column('employment_type', sa.Enum('FULL_TIME', 'PART_TIME', 'CONTRACT', 'VISITING', name='employment_type'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'ON_LEAVE', 'SUSPENDED', 'TERMINATED', name='teacher_status'), nullable=False),
    sa.Column('invited_from', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('institution_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.ForeignKeyConstraint(['invited_from'], ['invitations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_teachers_institution_id'), 'teachers', ['institution_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_teachers_institution_id'), table_name='teachers')
    op.drop_table('teachers')
    # ### end Alembic commands ###