export const institutionNavItems = [
    { label: "Dashboard", path: "/institution/dashboard" },
    { label: "Invitations", path: "/institution/invitations" },
    { label: "Teachers", path: "/institution/teachers" },
    { label: "Classes & teaching", path: "/institution/classes" },
    { label: "Students", path: "/institution/students" },
    { label: "User access", path: "/institution/users" },
    { label: "Attendance", path: "/institution/attendance" },
    { label: "Coursework", path: "/institution/coursework" },
    { label: "Course materials", path: "/institution/materials" },
    { label: "Scores", path: "/institution/scores" },
    { label: "Audit trail", path: "/institution/audit-logs" },
    { label: "Settings", path: "/institution/settings" },
    { label: "Account & security", path: "/institution/account" },
];
